name: Demo OneDeploy
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'onedeployjava'
          package: '../app.jar'
